francoismichel/ssh3

- cli/client/main.go
Set the selfsigned.ssh3 SNI as soon as a known host valid for selfsigned.ssh3 is present
> Set the selfsigned.ssh3 SNI as soon as a known host is valid for it

- cli/server/main.go
The server now logs the listening URL so that users deploying their server can debug more easily if needed.
> server: log the listening URL

- integration_tests/ssh3_test.go
We had a few issues with the integration tests run in Github Actions. These tests fail on pull requests where it should not fail (e.g. PR #45).
This PR adds a bit more checks to ensure the SSH3 server is still running before running every test spec.
It also ensures that the port forwarding test specs can be run in parrallel by making them use different port numbers.
> Integration tests server checks

- .github/workflows/build.yml
Rework the CI scripts to avoid using Github secrets as it prevents running these scripts on non-maintainer PRs.
> No secrets in build gh action

- .github/workflows/build.yml
The CI build script now generates an ed25519 key pair for testing in integration tests
> generate an ed25519 key for testuser

- integration_tests/ssh3_test.go
- util/util.go
This PR aims to fix #38. Some `pubkey`s passed to the function are not pointers, but are still valid keys. This commit fixes this bug by adding the non-pointer types to the switch. Furthermore, more debugging log prints are added.
I am submitting this PR as a draft, as integration tests do not pass (see [this comment](https://github.com/francoismichel/ssh3/pull/45#issuecomment-1859118891)).
> draft: fix(util): match non-pointer public key types

- cli/client/main.go
This PR fixes issue #35 where the client preferred the values from the configuration file `~/.ssh/config` instead of the CLI arguments. The new behaviour reflects the one used by OpenSSH, preferring the port from the CLI and the hostname from the configuration.
> fix(client): prefer CLI arguments, following OpenSSH behaviour

- .github/workflows/build.yml
- linux_server/authorized_identities.go
Until now, commented lines raised a logging at error level in authorized_indentities and authorized_keys. (#50) 
We fixed the logging to explicitly say that empty and commented lines are skipped.
Also added a test case with commented lines in authorized_identities
Fixes #50.
> handle commented and empty lines in authorized_indentities

- .github/workflows/build.yml
- cli/server/main.go
- integration_tests/ssh3_test.go
- util/linux_util/linux_user.go
Ensure we actually run the shell in login mode.
This makes bash process the ~/.profile file at startup.
> run the shell in login mode when an interactive session is run

- .github/workflows/build.yml
- auth/openid_connect.go
- channel.go
- cli/client/main.go
- cli/client/winsize/common.go
- cli/client/winsize/winsize.go
- cli/client/winsize/winsize_windows.go
- cli/server/main.go
- client.go
- conversation.go
- go.mod
- go.sum
- integration_tests/ssh3_test.go
- known_hosts.go
- linux_server/auth.go
- linux_server/authorized_identities.go
- linux_server/handlers.go
- message/channel_request.go
- message/message.go
- message/message_suite_test.go
- message/message_test.go
- resources_manager.go
- server.go
- util/linux_util/cmd.go
- util/linux_util/linux_user.go
- util/types.go
- util/util.go
- util/wire.go
- version.go
Used `gofmt` to rename `ssh3` to `github.com/francoismichel/ssh3`. The code hasn't been formatted so this resulted in a lot of whitespace changes.
> use fqdn for module

- cmd/ssh3/main.go
I ran [govanish](https://github.com/sivukhin/govanish) linter (it still in the WIP phase) against `ssh3` repo and it found a but: compiler eliminated following error check from the binary:
```go
remotePort, err = strconv.Atoi(array[1])
if err != nil {
return 0, nil, 0, fmt.Errorf("could not convert %s to int: %s", array[1], err)
} else if localPort > 0xFFFF {
return 0, nil, 0, fmt.Errorf("UDP port too large %d", remotePort)
}
```
```
2023/12/25 19:08:30 it seems like your code vanished from compiled binary: func=[parseAddrPort], file=[/home/sivukhin/code/ssh3/cmd/ssh3/main.go], line=[226], snippet:
return 0, nil, 0, fmt.Errorf("UDP port too large %d", remotePort)
```
This is a bug, because we need to validation `remotePort` value instead.
This PR fixes this minor issue.
> minor issue: fix remotePort validation

- util/unix_util/non_password_auth_user.go
SSH3 can incorrectly store a user's UID as a GID instead. This PR fixes that bug.
The responsible line is `gid, err := strconv.Atoi(u.Uid)`.
- Fix the bug by reading from `u.Gid` instead.
- Use the correct number of arguments in nearby error messages.
- Use `strconv.ParseUint` instead to reduce the number of type conversions.
- `go vet ./...` and `go test ./...` pass.
> Correctly parse user GID

- client/client.go
- cmd/ssh3/main.go
Client's ForwardTCP() and ForwardUDP() now return the local address they listen on to be used programatically afterwards.
> add return value to Client's ForwardTCP and ForwardUDP

- README.md
This PR proposes adding more measured language around SSH3's current security status. Making absolute security claims about an early prototype could be misleading without extensive analysis and review over time. 
To build community trust and encourage assistance accelerating SSH3's secure development, I've updated the messaging to:
- Note SSH3 is still an experimental proof-of-concept
- Advise against public Internet exposure in present form 
- Explicitly state that expert cryptographic review is still needed
- Call for collaboration to advance the protocol responsibly
I believe positioning SSH3's security more conservatively for now is prudent. It still shows intriguing promise improving on SSH2, but overstating protections too early can risk credibility and user security if …
> Proper security statements in README

- .github/workflows/build-release.yml
- .github/workflows/build.yml
- .github/workflows/test.yml
- cmd/ssh3/main.go
- conversation.go
- go.mod
- go.sum
- integration_tests/ssh3_test.go
- server.go
- util/types.go
This PR adds support for classical, secure, UDP-based Proxy-Jump.
Let's say we want to connect from A to C through B, B being the proxy. This works with the client located on A connecting to B and establishing UDP forwarding from towards C. By doing so, the client can send regular encrypted QUIC packets through the forwarded socket to connect to C. B cannot manipulate the QUIC packets are they are encrypted and authenticated.
The drawbacks of the approach are:
- quic-go datagram are slow
- we tunnel a congestion-controlled protocol through another congestion-controlled protocol which might cause problems, especially that quic-go is quite prompt to drop UDP datagrams.
So this will work the best for interactive sessions. If troughput is needed, we may want to look at #89 instead.
The …
> Support proxy jump

- cmd/ssh3-server/main.go
- util/util.go
Until now, the server used a classical go map for handling sessions that could lead to undefined behaviour (cf #80).
This PR fixes that by using a the `sync.Map` standard type.
> server: use sync.Map for managing running sessions

- cmd/ssh3/main.go
- conversation.go
- unix_server/auth.go
- util/types.go
The server now attaches a response body with its error responses that are different from 404 and 401.
This allows providing better information to the client and help them debug their setup.
> provide human-readable message with non-(200|401|404) server responses

- client_auth.go
- cmd/ssh3/main.go
- util/types.go
Add URLPath configuration option.
Some users may have troubles typing or remembering their URL path when it is complex, this config option is there so that the URL path does not have to always be specified explicitly.
> add URLPath config option

- client/client.go
- cmd/ssh3/main.go
- conversation.go
- go.mod
- integration_tests/ssh3_test.go
- unix_server/auth.go
- version.go
Until now, the version was strictly checked against the software version.
Now that the project gains in popularity and that a spec is coming, other people may try implementing the protocol.
This adds a version negotiation mechanism that is still quite strict.
* Add the concept of protocol *experimental spec version*, this currently implements the `alpha-00` experimental spec version.
* Do not check the *software* version during the negotiation, except for versions before `alpha-00`, where the implementation name then MUST be `francoismichel/ssh3`
* Right now, the server supports clients with version `alpha-00` and older, i.e. clients with implementation name `francoismichel/ssh3` and software version between `0.1.4` (included) and `0.1.5` (included)
* Future clients implementing future …
> add proper version negotiation

- README.md
- version.go
Proper version negotiation was added when developing software version 0.1.5. Instead of creating a new 0.1.5-rc that has version negotiation, it will be easier to just release version 0.1.6. Doing that, we know that every release before 0.1.6 has not version negotiation support.
> version 0.1.6-rc1

- unix_server/authorized_identities.go
Until now, the server panics upon an unknown identity in the authorized_identities/authorized_keys files. While this does not stop the server, this PR returns an error instead of panicking, which is cleaner.
> better handle unknown identities

- client/client.go
- cmd/ssh3/main.go
MacOS does not correctly set the DF bit on dual-stack UDP sockets (`udp` instead of `udp4` and `udp6`). This quic-go issue discusses that problem: https://github.com/quic-go/quic-go/issues/3793
without the DF bit set, quic-go won't perform path MTU discovery. Without path MTU discuvery, the default MTU will be too small to carry the quic-go initial packet (which could theoretically be 40 bytes smaller but quic-go fills the IP packet at maximum in its initial).
This PR fixes the problem on the client by not using a dual stack socket on MacOS.
The problem is not fixed on the MacOS server as servers often listen on dual-stack sockets.
Fixes #129
> do not use dual-stack UDP sockets on MacOS to enable MTU discovery

- auth/openid_connect.go
fix a bug in the PKCE process of OpenID Connect. The generated verifier had an invalid format.
> OIDC: fix PKCE random verifier generation

- cmd/ssh3.go
Enable PKCE by default since most OIDC endpoints provide this functionnality
> enable PKCE by default
